# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven

on:
  push:
    branches: [ test-jenkins-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: raghavgore.xyz
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deployments/raghav-testing
            eval "$(ssh-agent -s)"
            ssh-add -k ~/.ssh/ajay_paramlogic
            git pull origin master
            docker build -t test:0.0.2 .
            docker rm -f test
            docker run -d \
              --name test \
              --restart always \
              --net reverse-proxy \
              -p 8080:8080 \
              -e "TZ=Asia/Kolkata" \
              -e 'LETSENCRYPT_EMAIL=ajay.more@paramlogic.com' \
              -e 'LETSENCRYPT_HOST=raghavgore.xyz' \
              -e 'VIRTUAL_HOST=raghavgore.xyz' test:0.0.2
